#cloud-config
ssh_authorized_keys:
  - ssh-rsa ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCz3QctiBXVa0JorBAr85xVm0L6d5UjtuXcdbqS00Yvp/nSzxUyIKwHilJrQOqSTKTCRxuRpBI42bDeqNbRGjX2Kc8gbuporqQr9KG3LA+y8Xq8fNFLAXBxI8/QBG3FJrA+i6aYvRrRPjuD/RY4IBab3I1wFS5wchIk4794N7FiwfTz8S3hRyk2+Oj7ekzVeRUFJANgNX+ce4J7xfnktN/tk4X9gRBy/jwOXPOQH9+Ac5dlWqa44+DfXLh3spCRu+BjOfbIUBZSZJA7CRKA4jw1y4AVARrGhlXLeEF3aAHWFNerVi2bRGR4pX1B1ILMJL4H1WbqT+4vpNVKEZmKz9nd
